### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by somehowchris** [Ameobea/rocket_async_compression#1]
Hey man, :wink:

Lovely work, do you pin the rocket version to a git one for a reason? 

I forked the project and added some stuff, if you're in on have a PR I'm happy to help out :beer:

**Comment by Ameobea** [comment]
Hey!  The version is pinned just for a personal project I was using it with that was pinned to a Rocket version.  I'm totally down to unpin it now; I can update the project.  Would love to see your changes as well

**Comment by Ameobea** [comment]
Glanced at your branch and everything there looks like great changes; I'd be happy to upstream if you wanna make a PR :)

**Comment by somehowchris** [comment]
Sure, will remove the fork stuff from the readme and create a PR.

Any reason why the package isn't on crates.io?

**Comment by Ameobea** [comment]
I was hoping that it would be integrated into rocket itself, but I didn't see much interest/traction in the few/limited comments I made about it in issues on the rocket repo.  I could push it up there if you think it'd be useful to you or other people

**Comment by somehowchris** [comment]
Would be lovely.

Would also like to know if this action https://github.com/marketplace/actions/publish-crates really works that well with https://github.com/marketplace/actions/semantic-version and git tags

Well sergio seems to have had a difficult time personally but he will be back adcording to hist post https://github.com/SergioBenitez/Rocket/discussions/1957

**Comment by Ameobea** [comment]
Ok sounds good, I'll push it up to crates.io once your changes are merged in.  I'll probably skip the GH actions just because I don't foresee there being frequent changes to this code in the future.

**Comment by Ameobea** [comment]
Thanks for the improvements btw!
